### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by DLwbm123** [ai-med/point_recalibration#1]
Hi! Thanks for sharing such a fantastic paper. I am very interested in AD diagnosis. Could you please share the processed hippocampi point clouds data? Thanks!

**Comment by nsarasua** [comment]
> Hi! Thanks for sharing such a fantastic paper. I am very interested in AD diagnosis. Could you please share the processed hippocampi point clouds data? Thanks!

Hi,
Thank you for your interest in our work. Unfortunately the data cannot be shared since it belongs to ADNI. To get access to it, you have to go through their approval process. 
Cheers
